"""initial_schema

Revision ID: 461f23e8a12c
Revises:
Create Date: 2026-09-06 16:04:09.905748

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "461f23e8a12c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("wave_business_id", sa.String(), nullable=True),
        sa.Column("wave_access_token", sa.String(), nullable=True),
        sa.Column("wave_refresh_token", sa.String(), nullable=True),
        sa.Column("wave_token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("wave_equity_account_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency_code", sa.String(), nullable=False),
        sa.Column("receipt_file_path", sa.String(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_transactions_source_external_id"),
    )
    op.create_table(
        "wave_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("wave_account_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "wave_account_id", name="uq_wave_categories_company_wave_account_id"),
    )
    op.create_table(
        "allocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_personal", sa.Boolean(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("wave_category_id", sa.Uuid(), nullable=True),
        sa.Column("sync_status", sa.Enum("PENDING", "SYNCED", "FAILED", "IGNORED", name="sync_status", native_enum=False), nullable=False),
        sa.Column("wave_transaction_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wave_category_id"], ["wave_categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("allocations")
    op.drop_table("wave_categories")
    op.drop_table("transactions")
    op.drop_table("companies")
    # ### end Alembic commands ###
